# Generated by Django 5.0 on 2024-01-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_name_product_name_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_bid',
        ),
    ]
