# Generated by Django 5.0 on 2024-01-01 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_remove_auction_auto_bidding_enabled_auction_status_and_more'),
        ('bid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('auction', 'bidder')},
        ),
    ]
