# Generated by Django 5.0.1 on 2024-01-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_alter_bid_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set(),
        ),
    ]
